name: "dev_destroy"

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve the dev_destroy'
        required: true

jobs:
  terraform_dev_destroy:
    name: "dev_destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src/infrastructure

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: pre-init file
        run: bash ./format_validate_all.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -var-file="./env/dev/.terraform.tfvars" -backend-config="./env/dev/backend.tfvars"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="./env/dev/.terraform.tfvars"


      - name: Delete s3 objects recursively
        run: aws s3 rm s3://myoneandonly-dev-bucket --recursive

        
      - name: Terraform Destroy
        run: terraform destroy --auto-approve -var-file="./env/dev/.terraform.tfvars"