name: Terraform_dev

on:
  push:
    branches:
      - main
    paths:
      - 'src/infrastructure/**'
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve the Terraform_dev'
        required: true


jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    defaults:
      run:
        working-directory: src/infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pre-init file
        run: bash ./format_validate_all.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
      #   run: terraform init -backend-config=providers.tfvars
        run: terraform init -var-file="./env/dev/.terraform.tfvars" -backend-config="./env/dev/backend.tfvars"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="./env/dev/.terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="./env/dev/.terraform.tfvars" --auto-approve


